#!/usr/bin/env bash
set -euo pipefail
mkdir -p "images"
echo "Downloading naha-airport-arrival-hall.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Naha_Airport_new_international_terminal_20140428-1.JPG/1280px-Naha_Airport_new_international_terminal_20140428-1.JPG" -o "images/naha-airport-arrival-hall.jpg"
echo "Downloading naminoue-beach-naminoue-gu.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Naminoue-g%C5%AB_and_Naminoue_Beach_2018.jpg/1280px-Naminoue-g%C5%AB_and_Naminoue_Beach_2018.jpg" -o "images/naminoue-beach-naminoue-gu.jpg"
echo "Downloading kokusai-dori-street-international-street-night-view.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Kokusai-dori_Street_at_night_in_Naha_2022.jpg/1280px-Kokusai-dori_Street_at_night_in_Naha_2022.jpg" -o "images/kokusai-dori-street-international-street-night-view.jpg"
echo "Downloading cape-maeda-access-to-blue-cave.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Cape_Maeda_in_Onna%2C_Okinawa_pref%2C_Japan.JPG/1280px-Cape_Maeda_in_Onna%2C_Okinawa_pref%2C_Japan.JPG" -o "images/cape-maeda-access-to-blue-cave.jpg"
echo "Downloading mihama-town-resort-american-village.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Ferris_wheel_and_board_of_Mihama_Town_Resort_American_Village.JPG/1280px-Ferris_wheel_and_board_of_Mihama_Town_Resort_American_Village.JPG" -o "images/mihama-town-resort-american-village.jpg"
echo "Downloading chatan-sunset-beach.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Sunset_Beach_in_Chatan%2C_Okinawa_pref%2C_Japan.JPG/1280px-Sunset_Beach_in_Chatan%2C_Okinawa_pref%2C_Japan.JPG" -o "images/chatan-sunset-beach.jpg"
echo "Downloading manzamo-cliff-onna-okinawa.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Cape_Manza_in_Onna%2C_Okinawa_pref%2C_Japan_001.JPG/1280px-Cape_Manza_in_Onna%2C_Okinawa_pref%2C_Japan_001.JPG" -o "images/manzamo-cliff-onna-okinawa.jpg"
echo "Downloading okinawa-churaumi-aquarium-entrance.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Okinawa_Churaumi_Aquarium_Entrance.jpg/1280px-Okinawa_Churaumi_Aquarium_Entrance.jpg" -o "images/okinawa-churaumi-aquarium-entrance.jpg"
echo "Downloading kouri-bridge.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Kouri_Bridge_in_Nakijin%2C_Okinawa%2C_Japan.jpg/1280px-Kouri_Bridge_in_Nakijin%2C_Okinawa%2C_Japan.jpg" -o "images/kouri-bridge.jpg"
echo "Downloading shuri-castle.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Shuri-j%C5%8D_uchinaa_2018_B.jpg/1280px-Shuri-j%C5%8D_uchinaa_2018_B.jpg" -o "images/shuri-castle.jpg"
echo "Downloading umikaji-terrace-senagajima.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Senaga_Island_Umikaji_Terrace_in_Tomigusuku%2C_Okinawa%2C_Japan.jpg/1280px-Senaga_Island_Umikaji_Terrace_in_Tomigusuku%2C_Okinawa%2C_Japan.jpg" -o "images/umikaji-terrace-senagajima.jpg"
echo "Downloading gyokusendo-cave-okinawa-world.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Gyokusen-do_01.JPG/1280px-Gyokusen-do_01.JPG" -o "images/gyokusendo-cave-okinawa-world.jpg"
echo "Downloading makishi-public-market-interior.jpg ..."
curl -L --fail --retry 3 --connect-timeout 10 "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/The_provisional_market_of_the_First_Makishi_Public_Market_in_Naha_2022.jpg/1280px-The_provisional_market_of_the_First_Makishi_Public_Market_in_Naha_2022.jpg" -o "images/makishi-public-market-interior.jpg"
