#!/usr/bin/env python3
import os, sys, pathlib, requests
os.makedirs("images", exist_ok=True)
print("Downloading naha-airport-arrival-hall.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Naha_Airport_new_international_terminal_20140428-1.JPG/1280px-Naha_Airport_new_international_terminal_20140428-1.JPG", timeout=30)
open(os.path.join("images","naha-airport-arrival-hall.jpg"), "wb").write(response.content)
print("Downloading naminoue-beach-naminoue-gu.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Naminoue-g%C5%AB_and_Naminoue_Beach_2018.jpg/1280px-Naminoue-g%C5%AB_and_Naminoue_Beach_2018.jpg", timeout=30)
open(os.path.join("images","naminoue-beach-naminoue-gu.jpg"), "wb").write(response.content)
print("Downloading kokusai-dori-street-international-street-night-view.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Kokusai-dori_Street_at_night_in_Naha_2022.jpg/1280px-Kokusai-dori_Street_at_night_in_Naha_2022.jpg", timeout=30)
open(os.path.join("images","kokusai-dori-street-international-street-night-view.jpg"), "wb").write(response.content)
print("Downloading cape-maeda-access-to-blue-cave.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Cape_Maeda_in_Onna%2C_Okinawa_pref%2C_Japan.JPG/1280px-Cape_Maeda_in_Onna%2C_Okinawa_pref%2C_Japan.JPG", timeout=30)
open(os.path.join("images","cape-maeda-access-to-blue-cave.jpg"), "wb").write(response.content)
print("Downloading mihama-town-resort-american-village.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Ferris_wheel_and_board_of_Mihama_Town_Resort_American_Village.JPG/1280px-Ferris_wheel_and_board_of_Mihama_Town_Resort_American_Village.JPG", timeout=30)
open(os.path.join("images","mihama-town-resort-american-village.jpg"), "wb").write(response.content)
print("Downloading chatan-sunset-beach.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Sunset_Beach_in_Chatan%2C_Okinawa_pref%2C_Japan.JPG/1280px-Sunset_Beach_in_Chatan%2C_Okinawa_pref%2C_Japan.JPG", timeout=30)
open(os.path.join("images","chatan-sunset-beach.jpg"), "wb").write(response.content)
print("Downloading manzamo-cliff-onna-okinawa.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Cape_Manza_in_Onna%2C_Okinawa_pref%2C_Japan_001.JPG/1280px-Cape_Manza_in_Onna%2C_Okinawa_pref%2C_Japan_001.JPG", timeout=30)
open(os.path.join("images","manzamo-cliff-onna-okinawa.jpg"), "wb").write(response.content)
print("Downloading okinawa-churaumi-aquarium-entrance.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Okinawa_Churaumi_Aquarium_Entrance.jpg/1280px-Okinawa_Churaumi_Aquarium_Entrance.jpg", timeout=30)
open(os.path.join("images","okinawa-churaumi-aquarium-entrance.jpg"), "wb").write(response.content)
print("Downloading kouri-bridge.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Kouri_Bridge_in_Nakijin%2C_Okinawa%2C_Japan.jpg/1280px-Kouri_Bridge_in_Nakijin%2C_Okinawa%2C_Japan.jpg", timeout=30)
open(os.path.join("images","kouri-bridge.jpg"), "wb").write(response.content)
print("Downloading shuri-castle.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Shuri-j%C5%8D_uchinaa_2018_B.jpg/1280px-Shuri-j%C5%8D_uchinaa_2018_B.jpg", timeout=30)
open(os.path.join("images","shuri-castle.jpg"), "wb").write(response.content)
print("Downloading umikaji-terrace-senagajima.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Senaga_Island_Umikaji_Terrace_in_Tomigusuku%2C_Okinawa%2C_Japan.jpg/1280px-Senaga_Island_Umikaji_Terrace_in_Tomigusuku%2C_Okinawa%2C_Japan.jpg", timeout=30)
open(os.path.join("images","umikaji-terrace-senagajima.jpg"), "wb").write(response.content)
print("Downloading gyokusendo-cave-okinawa-world.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Gyokusen-do_01.JPG/1280px-Gyokusen-do_01.JPG", timeout=30)
open(os.path.join("images","gyokusendo-cave-okinawa-world.jpg"), "wb").write(response.content)
print("Downloading makishi-public-market-interior.jpg ...")
response = requests.get("https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/The_provisional_market_of_the_First_Makishi_Public_Market_in_Naha_2022.jpg/1280px-The_provisional_market_of_the_First_Makishi_Public_Market_in_Naha_2022.jpg", timeout=30)
open(os.path.join("images","makishi-public-market-interior.jpg"), "wb").write(response.content)
